apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-0035"
images:
- name: ghcr.io/kimnjang/slack-alert
  newTag: 0.0.35
- name: ghcr.io/kimnjang/train-mnist
  newTag: 0.0.35
resources:
- ../../base
vars:
- fieldref: {}
  name: EXPERIMENT_NAME
  objref:
    apiVersion: kubeflow.org/v1beta1
    kind: Experiment
    name: katib-experiment
