name: ci

on:
  push:
    tags:
      - "v*"
jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: master
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        
      - name: Find Suffix string
        run: |
          echo "SUFFIX=$VERSION//./" >> $GITHUB_ENV
          echo "version: $VERSION -> suffix: ${{ env.SUFFIX }}"

        env:
          VERSION: ${{ env.RELEASE_VERSION }}
          
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: train
          file: ./train/dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC}}/katib-mnist:${{ env.RELEASE_VERSION}}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Set new image tag
        run: |
          cd deployments/overlays/dev
          kustomize edit set image ghcr.io/${{ env.OWNER_LC }}/katib-mnist:${{ env.RELEASE_VERSION }}
          kustomize edit set namesuffix -- -${{env.SUFFIX}}
          git config --global user.name ${{ github.repository_owner }}
          git config --global user.email "jsuwan961205@gmail.com"
          git add .
          git commit -m 'Publish new version ${{ env.RELEASE_VERSION }} to dev'
          git push -u origin master
