name: ci

on:
  push:
    tags:
      - "v*"
jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repogitory_owner}}
          password: ${{ secrets.CR_PAT}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
        context: train
        file: ./train/dockerfile
        push: true
        tags: ghcr.io/${{ github.repogitory_owner}}/katib-mnist:${{ env.RELEASE_VERSION}}
