name: ci

on:
  push:
    tags:
      - "v*"
jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: master
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Find Suffix string
        run: |
          echo "SUFFIX=${VERSION//./}" >> $GITHUB_ENV
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
      - name: check suffix env
        run: |
          echo "version: $VERSION -> suffix: $SUFFIX"
        env:
          VERSION: ${{ env.RELEASE_VERSION }}
          SUFFIX: ${{ env.SUFFIX}}

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Experiment Build and push
        uses: docker/build-push-action@v2
        with:
          context: train
          file: ./train/dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC}}/train-mnist:${{ env.RELEASE_VERSION}}

      # - name: Alert Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: utils/slack-alert
      #     file: ./utils/slack-alert/dockerfile
      #     push: true
      #     tags: ghcr.io/${{ env.OWNER_LC}}/slack-alert:${{ env.RELEASE_VERSION}}
      #     build-args: SLACK_WEBHOOK_ARG=${{ secrets.SLACK_WEBHOOK }}
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Set new image tag
        run: |
          cd deployments/experiment/overlays/dev
          kustomize edit set image ghcr.io/${{ env.OWNER_LC }}/train-mnist:${{ env.RELEASE_VERSION }}
          kustomize edit set namesuffix -- -${{env.SUFFIX}}
          git config --global user.name ${{ github.repository_owner }}
          git config --global user.email "jsuwan961205@gmail.com"
          git add .
          git commit -m 'Publish new version ${{ env.RELEASE_VERSION }} to dev'
          git push -u origin master
